### PR TITLE
Amlogic libretech h3

### PR DESCRIPTION
**Pull request by montjoie**
This PR add support for 3 libretech boards.
Tested on lab-baylibre

### CODE REVIEW

**Comment by gctucker** [comment]
@montjoie Are these device types in LAVA upstream?

**Comment by montjoie** [comment]
merged via https://review.linaro.org/#/c/25943/ https://review.linaro.org/#/c/25944/ https://review.linaro.org/#/c/25945/

**Comment by gctucker** [comment]
Thanks, looks like this is ready to be merged and tested on staging.

**Comment by gctucker** [comment]
Tested on staging:
https://staging.kernelci.org/boot/id/5b34b296cf3a0faedfe969ce/
https://staging.kernelci.org/boot/id/5b34adf1cf3a0faedee969bf/
https://staging.kernelci.org/boot/id/5b34adf0cf3a0faedce969a3/

**Pull request merged**
