### PR TITLE
Add rk3399-puma-haikou device and theobroma-systems lab

### PR DESCRIPTION
**Pull request by jakob-tsd**
The RK3399 is an ARM64 6-core SoC made by Rockchip,
the Puma board (official name RK3399-Q7) is a compute
module made by Theobroma Systems.

The new lab has two Puma boards plugged into "Haikou" baseboards
that provide a USB-UART converter and power switching.

The LAVA instance is reachable at https://lava.theobroma-systems.com/ .

Linux mainline support was merged in v4.14-rc1
(commit 2c66fc34e9457ed10b56265e1dcf55c86d524e9e).
Earlier kernel versions have been blacklisted.

### CODE REVIEW

**Comment by khilman** [comment]
Have you submitted this LAVA device-type to mainline LAVA?  That is a pre-requisite before merging this into production.

**Comment by jakob-tsd** [comment]
No I have not - will do.

**Comment by jakob-tsd** [comment]
Posted for review at https://review.linaro.org/#/c/23514/

**Comment by mattface** [comment]
I've now merged the LAVA upstream config, thanks

**Pull request merged**
