### PR TITLE
lava-boot-v2: submit test jobs to BayLibre dev backend

### PR DESCRIPTION
**Pull request by khilman**
Create "simple" and "usb" plans and submit to the BayLibre dev
kernelCI backend.

Signed-off-by: Kevin Hilman <khilman@baylibre.com>

### CODE REVIEW

**Review by tomeuv — APPROVED** [review]
Sounds good to me, but would have been good to have the rationale for the change in the commit message, for the benefit of future readers.

**Comment by khilman** [comment]
Rationale is for testing a local, dev instance of kernelCI backend/frontend with continuous jobs from staging

**Comment by gctucker** [comment]
@khilman Looks like this should only be done when the lab name is `lab-baylibre-dev`, otherwise we'll have some bad surprise when this gets merged into production.

**Comment by khilman** [comment]
@gtucker what kind of bad surprise are you thinking of?

**Comment by mattface** [comment]
When this goes to production, it will create 2 sets of jobs, but it will submit the second set to the baylibre dev instance, note the callback url

**Comment by gtucker** [comment]
@khilman wrong developer. Think you were trying for @gctucker.

**Comment by gctucker** [comment]
@khilman Well do you also want to receive job notifications from production runs through the BayLibre API instance?

While it can make sense to run jobs with different instances on staging to test things, for production it would seem like all the jobs should only be using the main kernelci.org servers running the upstream master branch.

As far as I know the usual workflow for the backend/frontend is: develop on a standalone instance, get feature branches tested on staging servers and then merged into master branches.

**Comment by gctucker** [comment]
Hello @gtucker!  Thanks for the redirection :)

It looks like you're not using Github much, are you?  As I'm using the `gtucker` nickname in several other places I'd be interested if you were happy to let me change my Github user name to the one you're using.  That would make my life quite a bit easier and probably save you some unwanted mentions.

Sorry for hijacking this discussion, I couldn't find any other way to get in touch.  My email address is on my Github profile if you want to follow up on this.

**Comment by khilman** [comment]
@mattface I see what you're saying now.  I'll send a fixup PR.
@gctucker I only need it for staging/development.  I don't think it should happen in production.

**Pull request merged**
