### PR TITLE
T10344 replace device_map with test_configs and YAML data

### PR DESCRIPTION
**Pull request by gctucker**
Replace `lib.device_map` with `lib.test_configs` which contains all the data required to generate the LAVA v2 test definitions.  Update `lava-v2-jobs-from-api.py` accordingly to use it.  The key advantages are:
* scale better as new devices and new test plans keep being added
* better separate the test config data from the logic to generate the LAVA jobs
* make it possible to replace the static initialisation with a database backend if needed

This is a work-in-progress, early feedback is welcome.

Things left to be done:
* populate the full list of `test_configs` to match the current `device_map`
* test on staging
* drop all remaining LAVA v1 boards and support in general

### CODE REVIEW

**Comment by ana** [comment]
A couple of comments:
* Instead of using variables like: DEBIAN_URL at https://github.com/kernelci/lava-ci-staging/pull/96/commits/3006484b35dc40772a0fbe3da98b0a6313c5986f#diff-4e475214575e06341973b99068fbb4afR252) it would be better to use the debian release name.  This is a good idea in case we want to use rootfs from different debian releases at some moment. For example, right now we're using debian 9.0 (stretch), but once Debian 10.0 (buster) is released we might not want to change all the tests suites  for some reason.
* What about having all the Device types and test configurations info in a YAML file instead of having it in the code? This allows to track changes more easily in git. I'm not sold to the idea of having this information in a database in the future because this reason too.

**Comment by gctucker** [comment]
Thanks @ana, I think using YAML sounds like a good next step so I'll give that a try.  Also I'll adjust the Debian file system names while doing that.

_Side notes_
Using a DB can have some advantages: having the definitions of the test plans, device types etc... available in the backend may enable more advanced features when dealing with test results.  For example, some test plan or device properties could be used both while generating the jobs and while receiving the results (I don't think we need this now, but if we hit some problems with the current approach then we may consider using the backend this way).  Also, if we need to query or update a large dataset, a database works better than YAML, regardless of whether it's in the backend or not.  We could have command line tools to update the YAML data automatically though if needed.

**Comment by mattface** [comment]
On 13 August 2018 at 15:03, Guillaume Tucker <notifications@github.com> wrote:
>
> Thanks @ana, I think using YAML sounds like a good next step so I'll give that a try. Also I'll adjust the Debian file system names while doing that.
>
> Side notes
> Using a DB can have some advantages: having the definitions of the test plans, device types etc... available in the backend may enable more advanced features when dealing with test results. For example, some test plan or device properties could be used both while generating the jobs and while receiving the results (I don't think we need this now, but if we hit some problems with the current approach then we may consider using the backend this way). Also, if we need to query or update a large dataset, a database works better than YAML, regardless of whether it's in the backend or not. We could have command line tools to update the YAML data automatically though if needed.


It can also be useful for generating UI pages showing what tests we
run on what hardware etc.

**Comment by gctucker** [comment]
@ana This new WIP version uses YAML rather than Python initialisers.  Also the Debian file systems are now called `debian_stretch_ramdisk` instead of `debian_ramdisk` etc...

**Comment by gctucker** [comment]
Note: I think the labs could also be in the YAML definitions, with attributes such as filters for the test plans to run, LAVA jobs priorities etc... and essentially remove `lava-boot-v2.sh` which has all this config data atm.  This might be done as a follow-up PR though.

**Comment by ana** [comment]
> Note: I think the labs could also be in the YAML definitions, with attributes such as filters for the test plans to run, LAVA jobs priorities etc... and essentially remove `lava-boot-v2.sh` which has all this config data atm. This might be done as a follow-up PR though.

Yes, I agree it's a good idea to move that and do it in a follow-up PR.

**Review by khilman — APPROVED** [review]

**Comment by gctucker** [comment]
Tested OK on staging:
https://staging.kernelci.org/boot/all/job/gtucker/branch/kernelci-test/kernel/kernelci-test-076-15-g5e2701d8808f/

I've started adding some docstrings, there's probably still a bit of work needed wrt documentation and YAML schema.

**Pull request merged**
